Add types for admin-rebalance subcommands
minio/madmin-go pull request #106
Opened 2022-08-05 22:26 UTC by krisis

.. and for tracing rebalance internal functions.

2022-08-09 18:47 UTC, harshavardhana approved these changes

2022-08-11 07:53 UTC, vadmeste reviewed
One comment

2022-08-11 07:53 UTC, vadmeste commented on rebalance.go
> +		ARN             uuid.UUID
This doesn't have json tags like MarshalJSON(), it doesn't seem this will work correctly

2022-08-11 18:39 UTC, harshavardhana requested changes

2022-08-11 18:39 UTC, harshavardhana commented on rebalance.go
> +		ARN uuid.UUID `json:"arn"`
ARN has a specific meaning in AWS S3 spec not sure it would be wise to use UUID as ARN - you can just call it as ID @krisis

2022-08-16 16:54 UTC, harshavardhana approved these changes

2022-09-29 18:17 UTC, harshavardhana commented
Please rebase the PR @krisis

2022-10-06 06:06 UTC, merged

2022-10-06 06:06 UTC, harshavardhana commented
v1.6.1 is pushed @krisis FYI.