Add support for site replication resync
minio/madmin-go pull request #129
Opened 2022-09-24 00:15 UTC by poornas

2022-09-29 18:16 UTC, harshavardhana requested changes

2022-09-29 18:16 UTC, harshavardhana commented on cluster-commands.go
> +	resp, err := adm.executeMethod(ctx, http.MethodGet, reqData)
As discussed we can move this to `Metrics()` API and provide realtime metrics for this and along with any `mc admin trace --call replication` activity.

2022-10-06 15:30 UTC, vadmeste commented
@poornas can you resolve conflicts here ?

2022-10-16 04:43 UTC, harshavardhana approved these changes

2022-10-16 04:44 UTC, merged