client to server bandwidth measurement API
minio/madmin-go pull request #152
Opened 2022-11-10 09:24 UTC by harshavardhana

2022-11-16 22:55 UTC, harshavardhana commented
PTAL @vadmeste @klauspost

2022-11-16 22:56 UTC, harshavardhana commented
NOTE: the measurement here is only for throughput so there is no RX/TX involved in this.

2022-11-17 17:02 UTC, klauspost commented
Shouldn't we add the download benchmark right away? Do we have a speedtest endpoint we can pull data from?

2022-11-17 17:54 UTC, harshavardhana commented
> Shouldn't we add the download benchmark right away? Do we have a speedtest endpoint we can pull data from?
> 
> In many cases bandwidth will be async.

There is no reason to do that you can saturate the link by simply sending data @klauspost - since its pure network doesn't need write/read like differentiation IMO.

2022-11-17 18:10 UTC, klauspost commented
What do you mean? There are many async connection types out there. Measuring upload only gives half the picture.

2022-11-17 18:56 UTC, harshavardhana commented
> What do you mean? There are many async connection types out there. Measuring upload only gives half the picture.

We are only validating what is the network throughput from client to server, this doesn't measure anything else. Of course, the server is not sending data back to the client here, but that is not useful IMO. 

Because all we care to show is the X bandwidth fully saturated value what is possible from client to server. In a full duplex connection such as 100g the 12GiB/sec value itself shows what is the overall bandwidth.

2022-11-22 17:47 UTC, harshavardhana commented
any other questions @klauspost @vadmeste ?

2022-11-23 12:10 UTC, klauspost requested changes
> In a full duplex connection such as 100g, the 12GiB/sec value itself shows what is the overall bandwidth.

There are many async connections that do not provide close to the same upload/download speeds.

I don't mind that you don't want to add download test now. But then let's name the field what it is, so we can add download later.

2022-11-23 12:10 UTC, klauspost commented on perf-net.go
> +	Bandwidth uint64 `json:"bw"`
```suggestion
	UploadBandwidth uint64 `json:"up_bps"`
```

2023-01-23 20:33 UTC, harshavardhana commented
Will re-submit when we need this..

2023-01-23 20:33 UTC, closed without merging