speedtest: Add keep-data flag to keep the generated data
minio/madmin-go pull request #174
Opened 2023-02-14 09:44 UTC by vadmeste

For mc support perf <alias>, the default behavior is to remove 
the generated objects when doing object speed test. Adding
 a flag to offer a possibility to keep the generated data, so we 
can have a way to quickly generate data of any size.

e.g.
mc support perf object <alias> --duration 30m --keep-data --size 1K

2023-02-14 10:10 UTC, harshavardhana requested changes

2023-02-14 10:10 UTC, harshavardhana commented on perf-object.go
> +	KeepData     bool          // Avoid cleanup after running an object speed test
```suggestion
	NoClear     bool          // Avoid cleanup after running an object speed test
```

2023-02-14 10:10 UTC, harshavardhana commented on perf-object.go
> +	if opts.KeepData {
```suggestion
	if opts.NoClear {
```

2023-02-14 10:10 UTC, harshavardhana commented on perf-object.go
> +		queryVals.Set("keep-data", "true")
```suggestion
		queryVals.Set("noclear", "true")
```

2023-02-14 11:13 UTC, vadmeste commented
@harshavardhana it looks like this PR is overkill since a single 'warp' cli command is enough, what do you think?

2023-02-17 10:44 UTC, vadmeste commented
We just this for this PR https://github.com/actions/go-versions/pull/70 to be merged to fix vulncheck complaints

2023-02-17 12:13 UTC, vadmeste commented
@harshavardhana can you take a look ?

2023-02-17 13:19 UTC, harshavardhana approved these changes

2023-02-17 13:20 UTC, merged