Add "name" and "description" params to service acc
minio/madmin-go pull request #194
Opened 2023-05-10 02:45 UTC by donatello

- Names may be 32 chars and may contain alphanumeric chars, hyphens and underscores

- Description may be at most 256 bytes long and have arbitrary (UTF-8 encoded) content.

- Remove the comment parameter as the term may cause confusion.

2023-05-10 03:00 UTC, donatello commented
Needed for https://github.com/minio/minio/pull/17172 and https://github.com/minio/mc/pull/4569

2023-05-10 07:57 UTC, harshavardhana requested changes

2023-05-10 07:57 UTC, harshavardhana commented on user-commands.go
> +	// To be deprecated in favor of description
```suggestion
	// Deprecated: Use Description instead
```

2023-05-12 21:51 UTC, donatello commented
@harshavardhana This is ready

2023-05-13 00:09 UTC, harshavardhana approved these changes

2023-05-13 00:09 UTC, merged