support perf site replication
minio/madmin-go pull request #200
Opened 2023-06-20 15:18 UTC by jiuker

support perf site replication

2023-06-20 21:55 UTC, poornas commented on perf-site-replication.go
> +type SiteReplicationperfNodeResult struct {
```suggestion
type SiteReplicationPerfNodeResult struct {
```

2023-06-20 21:55 UTC, poornas commented on perf-site-replication.go
> +type SiteReplicationperfResult struct {
```suggestion
type SiteReplicationPerfResult struct {
```

2023-06-22 09:41 UTC, klauspost commented on perf-site-replication.go
> +	Error    string `json:"error,omitempty"`
Don't we need a time indication here, so we know the time frame spent transferring RX/TX?

I feel that should be added for completeness, so we don't have to rely on the query to parse the result.

2023-06-22 09:41 UTC, klauspost commented on perf-site-replication.go
> +	Error    string `json:"error,omitempty"`
Don't we measure ping latency? Or is that out of scope?

2023-06-22 10:01 UTC, klauspost commented on perf-site-replication.go
> +	Error    string `json:"error,omitempty"`
Also add the number of concurrent connections per peer.

2023-06-22 17:20 UTC, harshavardhana requested changes

2023-06-22 17:20 UTC, harshavardhana commented on perf-site-replication.go
> +	TxDurMs   uint64 `json:"txDurMs"`
```suggestion
	TXTotalDuration   time.Duration `json:"txTotalDuration"`
```

2023-06-22 17:20 UTC, harshavardhana commented on perf-site-replication.go
> +	RxDurMs   uint64 `json:"rxDurMs"`
```suggestion
	RXTotalDuration   time.Duration `json:"rxTotalDuration"`
```

2023-06-22 17:20 UTC, harshavardhana commented on perf-site-replication.go
> +	TX        uint64 `json:"tx"`
```suggestion
	TX        uint64 `json:"tx"` // transfer rate in bytes
```

2023-06-22 17:20 UTC, harshavardhana commented on perf-site-replication.go
> +	RX        uint64 `json:"rx"`
```suggestion
	RX        uint64 `json:"rx"` // received rate in bytes 
```

2023-06-26 23:13 UTC, harshavardhana approved these changes

2023-06-26 23:14 UTC, merged