feat:add field for TTFB
minio/madmin-go pull request #220
Opened 2023-08-23 08:04 UTC by jiuker

add field for TTFB

2023-08-23 15:44 UTC, klauspost reviewed
What is up with all the removed dependencies?

2023-08-23 15:48 UTC, harshavardhana requested changes

2023-08-23 15:48 UTC, harshavardhana commented on perf-site-replication.go
> +	if s.readCounter == 1 {
use switch case instead of double `if` @jiuker

2023-08-23 15:48 UTC, harshavardhana commented on perf-site-replication.go
> +		s.TimeToFirstByte = time.Now().Sub(s.startTime)
```suggestion
		s.TimeToFirstByte = time.Since(s.startTime)
```

2023-08-23 15:48 UTC, harshavardhana commented on perf-site-replication.go
> +		return 0, io.EOF
You do not need to only send the first byte via this reader instead it must be the first Read() itself how much was received by the other end. 

Look at the server-side implementation of how a response recorder is used to calculate time to the first byte.

2023-08-31 16:07 UTC, harshavardhana requested changes
don't use only `go mod tidy` - please use `go mod tidy -compat=1.19`

2023-09-19 08:10 UTC, jiuker commented
@harshavardhana PTAL

2023-10-31 03:18 UTC, closed without merging