Added structs for bucket throttle
minio/madmin-go pull request #252
Opened 2023-12-04 13:29 UTC by shtripat

2023-12-04 14:32 UTC, harshavardhana requested changes
We do not need a new API simple extend SetBucketQuota() @shtripat

2023-12-05 03:50 UTC, shtripat commented
> We do not need a new API simple extend SetBucketQuota() @shtripat

IIUC, its like we add `concurrent-req-count` and `apis` options to `mc quota set` command, right?

2023-12-11 19:41 UTC, harshavardhana requested changes

2023-12-11 19:41 UTC, harshavardhana commented on quota-commands.go
>  type BucketQuota struct {
Bring a helper function that tells you if throttling is enabled or not

2023-12-19 12:19 UTC, closed without merging