tier: Add support of service principal to Azure
minio/madmin-go pull request #254
Opened 2023-12-07 04:05 UTC by vadmeste

In order to support service principal account when configuring tiering to a Azure storage

2023-12-07 04:17 UTC, harshavardhana requested changes

2023-12-07 04:17 UTC, harshavardhana commented on tier-azure.go
> +func (ti TierAzure) IsServicePrincipalEnabled() bool {
```suggestion
func (ti TierAzure) IsSPAuthEnabled() bool {
```

2023-12-07 18:30 UTC, vadmeste commented on tier-azure.go
> +func (ti TierAzure) IsServicePrincipalEnabled() bool {
Done!

2023-12-07 21:04 UTC, harshavardhana requested changes

2023-12-07 21:04 UTC, harshavardhana commented on tier-azure.go
> +type ServicePrincipalAuth struct {
```suggestion
// ServicePrincipalAuth - add a comment
type ServicePrincipalAuth struct {
```

2023-12-11 19:23 UTC, krisis approved these changes

2023-12-11 19:26 UTC, merged