tier: Add validation to tier configuration
minio/madmin-go pull request #256
Opened 2023-12-18 22:32 UTC by vadmeste

Bonus, also add missing aws role web identity and role ARN when editing the tier

2023-12-18 22:49 UTC, harshavardhana requested changes

2023-12-18 22:49 UTC, harshavardhana commented on tier-azure.go
>  func (ti TierAzure) IsSPEnabled() bool {
```suggestion
func (t TierAzure) IsSPEnabled() bool {
```

2023-12-18 23:02 UTC, harshavardhana approved these changes

2023-12-19 00:54 UTC, vadmeste commented
Rewrote this as per @krisis ask; we are going to make the validation in one place, in the server side. Meanwhile, this PR will only contain the new fields in the tier config data structure.

2023-12-21 00:49 UTC, krisis approved these changes

2023-12-21 01:07 UTC, merged