Make ParsePrometheusResults method public
minio/madmin-go pull request #259
Opened 2024-01-05 22:46 UTC by cesnietor

We'll be using this method in other minIO products so sharing this so that we don't have to duplicate code. It already has tests.

2024-01-05 23:00 UTC, pjuarezd approved these changes

2024-01-06 01:48 UTC, prakashsvmx approved these changes

2024-01-06 21:59 UTC, harshavardhana requested changes
I am not sure why this is implemented this way, we should fix the implementation first.

```
go func() {
		defer close(errChan)
		err = prom2json.ParseReader(reader, mfChan)
		if err != nil {
			errChan <- err
		}
	}()
	for mf := range mfChan {
		results = append(results, prom2json.NewFamily(mf))
	}
	if err := <-errChan; err != nil {
		return nil, err
	}
	return results, nil
```

There is no reason to have a go-routine for a blocking call. 

Let's rewrite it like this clean and simple. 

```go
func ParsePrometheusResults(reader io.Reader) (results []*prom2json.Family, err error) {
        // We could do further content-type checks here, but the                                                                                                                                                   
        // fallback for now will anyway be the text format                                                                                                                                                         
        // version 0.0.4, so just go for it and see if it works.                                                                                                                                                   
        var parser expfmt.TextParser
        metricFamilies, err := parser.TextToMetricFamilies(reader)
        if err != nil {
                return nil, fmt.Errorf("reading text format failed: %v", err)
	}
        results = make([]*prom2json.Family, 0, len(metricFamilies))
	for _, mf := range metricFamilies {
		results = append(results, prom2json.NewFamily(mf))
	}
        return results, nil
}
```

2024-01-18 18:50 UTC, harshavardhana commented
@cesnietor ^^ PTAL

2024-01-19 03:18 UTC, harshavardhana commented
This is merged to the master with cleaner implementation.

2024-01-19 03:18 UTC, closed without merging