admin-info: include per-tier stats
minio/madmin-go pull request #40
Opened 2021-10-08 00:20 UTC by krisis

2021-10-08 22:59 UTC, harshavardhana requested changes

2021-10-08 22:59 UTC, harshavardhana commented on info-commands.go
> +	AllTierStats map[string]TierStats `json:"allTierStats,omitempty"`
```suggestion
	TiersStats map[string]TierStats `json:"tiersStats,omitempty"`
```

2021-10-11 09:10 UTC, vadmeste approved these changes
LGTM

2021-10-12 13:21 UTC, klauspost approved these changes
LGTM

2021-10-12 18:09 UTC, merged