add support for drive speedtest
minio/madmin-go pull request #68
Opened 2022-01-26 04:36 UTC by wlan0

2022-01-26 07:48 UTC, harshavardhana requested changes

2022-01-26 07:48 UTC, harshavardhana commented on speedtest.go
You need to run `gofumpt` https://github.com/mvdan/gofumpt - looks like an unexpected indentation here.

2022-01-27 07:06 UTC, wlan0 commented
@harshavardhana updated the PR

2022-01-28 00:11 UTC, harshavardhana approved these changes

2022-01-28 00:12 UTC, harshavardhana approved these changes

2022-01-28 00:12 UTC, merged