Add minio tier type
minio/madmin-go pull request #73
Opened 2022-03-03 19:49 UTC by krisis

2022-03-03 22:05 UTC, krisis commented
This is a breaking change. It modifies TierConfig to include *TierMinIO type. It also replaces TierConfigV1 constant with TierConfigVer.

2022-03-03 23:43 UTC, poornas approved these changes

2022-03-08 00:24 UTC, harshavardhana approved these changes

2022-03-08 01:44 UTC, harshavardhana requested changes
Reverting certain changes as discussed @krisis

2022-03-11 01:37 UTC, harshavardhana approved these changes

2022-03-11 01:37 UTC, merged