Change support profile API
minio/madmin-go pull request #77
Opened 2022-03-31 00:21 UTC by poornas

Remove DownloadingProfile API, and merging functionality into
Profile API call.

2022-03-31 09:24 UTC, vadmeste approved these changes
LGTM

2022-04-20 17:28 UTC, harshavardhana requested changes

2022-04-20 17:28 UTC, harshavardhana commented on profiling-commands.go
> +//  DownloadProfilingData makes an admin call to download profiling data of a standalone
```suggestion
// DownloadProfilingData makes an admin call to download profiling data of a standalone
```

2022-04-20 17:30 UTC, harshavardhana requested changes

2022-04-20 17:30 UTC, harshavardhana commented on profiling-commands.go
>  // StartProfiling makes an admin call to remotely start profiling on a standalone
```suggestion
// Deprecated: StartProfiling makes an admin call to remotely start profiling on a standalone
```

2022-04-20 17:30 UTC, harshavardhana commented on profiling-commands.go
> +// server or the whole cluster in  case of a distributed setup. [DEPRECATED]
```suggestion
// server or the whole cluster in case of a distributed setup.
```

2022-04-20 17:30 UTC, harshavardhana commented on profiling-commands.go
>  // DownloadProfilingData makes an admin call to download profiling data of a standalone
```suggestion
// Deprecated: DownloadProfilingData makes an admin call to download profiling data of a standalone
```

2022-04-20 17:30 UTC, harshavardhana commented on profiling-commands.go
> +// server or of the whole cluster in  case of a distributed setup.[DEPRECATED]
```suggestion
// server or of the whole cluster in case of a distributed setup.
```

2022-04-20 17:32 UTC, harshavardhana approved these changes

2022-04-20 17:41 UTC, merged